# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/project/github/CircuitSimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/project/github/CircuitSimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/project/github/CircuitSimulator/CMakeFiles /home/martin/project/github/CircuitSimulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/project/github/CircuitSimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nanotekspice

# Build rule for target.
nanotekspice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanotekspice
.PHONY : nanotekspice

# fast build rule for target.
nanotekspice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/build
.PHONY : nanotekspice/fast

src/chips/2716.o: src/chips/2716.cpp.o
.PHONY : src/chips/2716.o

# target to build an object file
src/chips/2716.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/2716.cpp.o
.PHONY : src/chips/2716.cpp.o

src/chips/2716.i: src/chips/2716.cpp.i
.PHONY : src/chips/2716.i

# target to preprocess a source file
src/chips/2716.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/2716.cpp.i
.PHONY : src/chips/2716.cpp.i

src/chips/2716.s: src/chips/2716.cpp.s
.PHONY : src/chips/2716.s

# target to generate assembly for a file
src/chips/2716.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/2716.cpp.s
.PHONY : src/chips/2716.cpp.s

src/chips/4001.o: src/chips/4001.cpp.o
.PHONY : src/chips/4001.o

# target to build an object file
src/chips/4001.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4001.cpp.o
.PHONY : src/chips/4001.cpp.o

src/chips/4001.i: src/chips/4001.cpp.i
.PHONY : src/chips/4001.i

# target to preprocess a source file
src/chips/4001.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4001.cpp.i
.PHONY : src/chips/4001.cpp.i

src/chips/4001.s: src/chips/4001.cpp.s
.PHONY : src/chips/4001.s

# target to generate assembly for a file
src/chips/4001.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4001.cpp.s
.PHONY : src/chips/4001.cpp.s

src/chips/4008.o: src/chips/4008.cpp.o
.PHONY : src/chips/4008.o

# target to build an object file
src/chips/4008.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4008.cpp.o
.PHONY : src/chips/4008.cpp.o

src/chips/4008.i: src/chips/4008.cpp.i
.PHONY : src/chips/4008.i

# target to preprocess a source file
src/chips/4008.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4008.cpp.i
.PHONY : src/chips/4008.cpp.i

src/chips/4008.s: src/chips/4008.cpp.s
.PHONY : src/chips/4008.s

# target to generate assembly for a file
src/chips/4008.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4008.cpp.s
.PHONY : src/chips/4008.cpp.s

src/chips/4011.o: src/chips/4011.cpp.o
.PHONY : src/chips/4011.o

# target to build an object file
src/chips/4011.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4011.cpp.o
.PHONY : src/chips/4011.cpp.o

src/chips/4011.i: src/chips/4011.cpp.i
.PHONY : src/chips/4011.i

# target to preprocess a source file
src/chips/4011.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4011.cpp.i
.PHONY : src/chips/4011.cpp.i

src/chips/4011.s: src/chips/4011.cpp.s
.PHONY : src/chips/4011.s

# target to generate assembly for a file
src/chips/4011.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4011.cpp.s
.PHONY : src/chips/4011.cpp.s

src/chips/4013.o: src/chips/4013.cpp.o
.PHONY : src/chips/4013.o

# target to build an object file
src/chips/4013.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4013.cpp.o
.PHONY : src/chips/4013.cpp.o

src/chips/4013.i: src/chips/4013.cpp.i
.PHONY : src/chips/4013.i

# target to preprocess a source file
src/chips/4013.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4013.cpp.i
.PHONY : src/chips/4013.cpp.i

src/chips/4013.s: src/chips/4013.cpp.s
.PHONY : src/chips/4013.s

# target to generate assembly for a file
src/chips/4013.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4013.cpp.s
.PHONY : src/chips/4013.cpp.s

src/chips/4017.o: src/chips/4017.cpp.o
.PHONY : src/chips/4017.o

# target to build an object file
src/chips/4017.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4017.cpp.o
.PHONY : src/chips/4017.cpp.o

src/chips/4017.i: src/chips/4017.cpp.i
.PHONY : src/chips/4017.i

# target to preprocess a source file
src/chips/4017.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4017.cpp.i
.PHONY : src/chips/4017.cpp.i

src/chips/4017.s: src/chips/4017.cpp.s
.PHONY : src/chips/4017.s

# target to generate assembly for a file
src/chips/4017.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4017.cpp.s
.PHONY : src/chips/4017.cpp.s

src/chips/4030.o: src/chips/4030.cpp.o
.PHONY : src/chips/4030.o

# target to build an object file
src/chips/4030.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4030.cpp.o
.PHONY : src/chips/4030.cpp.o

src/chips/4030.i: src/chips/4030.cpp.i
.PHONY : src/chips/4030.i

# target to preprocess a source file
src/chips/4030.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4030.cpp.i
.PHONY : src/chips/4030.cpp.i

src/chips/4030.s: src/chips/4030.cpp.s
.PHONY : src/chips/4030.s

# target to generate assembly for a file
src/chips/4030.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4030.cpp.s
.PHONY : src/chips/4030.cpp.s

src/chips/4040.o: src/chips/4040.cpp.o
.PHONY : src/chips/4040.o

# target to build an object file
src/chips/4040.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4040.cpp.o
.PHONY : src/chips/4040.cpp.o

src/chips/4040.i: src/chips/4040.cpp.i
.PHONY : src/chips/4040.i

# target to preprocess a source file
src/chips/4040.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4040.cpp.i
.PHONY : src/chips/4040.cpp.i

src/chips/4040.s: src/chips/4040.cpp.s
.PHONY : src/chips/4040.s

# target to generate assembly for a file
src/chips/4040.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4040.cpp.s
.PHONY : src/chips/4040.cpp.s

src/chips/4069.o: src/chips/4069.cpp.o
.PHONY : src/chips/4069.o

# target to build an object file
src/chips/4069.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4069.cpp.o
.PHONY : src/chips/4069.cpp.o

src/chips/4069.i: src/chips/4069.cpp.i
.PHONY : src/chips/4069.i

# target to preprocess a source file
src/chips/4069.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4069.cpp.i
.PHONY : src/chips/4069.cpp.i

src/chips/4069.s: src/chips/4069.cpp.s
.PHONY : src/chips/4069.s

# target to generate assembly for a file
src/chips/4069.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4069.cpp.s
.PHONY : src/chips/4069.cpp.s

src/chips/4071.o: src/chips/4071.cpp.o
.PHONY : src/chips/4071.o

# target to build an object file
src/chips/4071.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4071.cpp.o
.PHONY : src/chips/4071.cpp.o

src/chips/4071.i: src/chips/4071.cpp.i
.PHONY : src/chips/4071.i

# target to preprocess a source file
src/chips/4071.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4071.cpp.i
.PHONY : src/chips/4071.cpp.i

src/chips/4071.s: src/chips/4071.cpp.s
.PHONY : src/chips/4071.s

# target to generate assembly for a file
src/chips/4071.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4071.cpp.s
.PHONY : src/chips/4071.cpp.s

src/chips/4081.o: src/chips/4081.cpp.o
.PHONY : src/chips/4081.o

# target to build an object file
src/chips/4081.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4081.cpp.o
.PHONY : src/chips/4081.cpp.o

src/chips/4081.i: src/chips/4081.cpp.i
.PHONY : src/chips/4081.i

# target to preprocess a source file
src/chips/4081.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4081.cpp.i
.PHONY : src/chips/4081.cpp.i

src/chips/4081.s: src/chips/4081.cpp.s
.PHONY : src/chips/4081.s

# target to generate assembly for a file
src/chips/4081.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4081.cpp.s
.PHONY : src/chips/4081.cpp.s

src/chips/4094.o: src/chips/4094.cpp.o
.PHONY : src/chips/4094.o

# target to build an object file
src/chips/4094.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4094.cpp.o
.PHONY : src/chips/4094.cpp.o

src/chips/4094.i: src/chips/4094.cpp.i
.PHONY : src/chips/4094.i

# target to preprocess a source file
src/chips/4094.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4094.cpp.i
.PHONY : src/chips/4094.cpp.i

src/chips/4094.s: src/chips/4094.cpp.s
.PHONY : src/chips/4094.s

# target to generate assembly for a file
src/chips/4094.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4094.cpp.s
.PHONY : src/chips/4094.cpp.s

src/chips/4512.o: src/chips/4512.cpp.o
.PHONY : src/chips/4512.o

# target to build an object file
src/chips/4512.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4512.cpp.o
.PHONY : src/chips/4512.cpp.o

src/chips/4512.i: src/chips/4512.cpp.i
.PHONY : src/chips/4512.i

# target to preprocess a source file
src/chips/4512.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4512.cpp.i
.PHONY : src/chips/4512.cpp.i

src/chips/4512.s: src/chips/4512.cpp.s
.PHONY : src/chips/4512.s

# target to generate assembly for a file
src/chips/4512.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4512.cpp.s
.PHONY : src/chips/4512.cpp.s

src/chips/4514.o: src/chips/4514.cpp.o
.PHONY : src/chips/4514.o

# target to build an object file
src/chips/4514.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4514.cpp.o
.PHONY : src/chips/4514.cpp.o

src/chips/4514.i: src/chips/4514.cpp.i
.PHONY : src/chips/4514.i

# target to preprocess a source file
src/chips/4514.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4514.cpp.i
.PHONY : src/chips/4514.cpp.i

src/chips/4514.s: src/chips/4514.cpp.s
.PHONY : src/chips/4514.s

# target to generate assembly for a file
src/chips/4514.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4514.cpp.s
.PHONY : src/chips/4514.cpp.s

src/chips/4801.o: src/chips/4801.cpp.o
.PHONY : src/chips/4801.o

# target to build an object file
src/chips/4801.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4801.cpp.o
.PHONY : src/chips/4801.cpp.o

src/chips/4801.i: src/chips/4801.cpp.i
.PHONY : src/chips/4801.i

# target to preprocess a source file
src/chips/4801.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4801.cpp.i
.PHONY : src/chips/4801.cpp.i

src/chips/4801.s: src/chips/4801.cpp.s
.PHONY : src/chips/4801.s

# target to generate assembly for a file
src/chips/4801.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/4801.cpp.s
.PHONY : src/chips/4801.cpp.s

src/chips/clock.o: src/chips/clock.cpp.o
.PHONY : src/chips/clock.o

# target to build an object file
src/chips/clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/clock.cpp.o
.PHONY : src/chips/clock.cpp.o

src/chips/clock.i: src/chips/clock.cpp.i
.PHONY : src/chips/clock.i

# target to preprocess a source file
src/chips/clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/clock.cpp.i
.PHONY : src/chips/clock.cpp.i

src/chips/clock.s: src/chips/clock.cpp.s
.PHONY : src/chips/clock.s

# target to generate assembly for a file
src/chips/clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/clock.cpp.s
.PHONY : src/chips/clock.cpp.s

src/chips/false.o: src/chips/false.cpp.o
.PHONY : src/chips/false.o

# target to build an object file
src/chips/false.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/false.cpp.o
.PHONY : src/chips/false.cpp.o

src/chips/false.i: src/chips/false.cpp.i
.PHONY : src/chips/false.i

# target to preprocess a source file
src/chips/false.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/false.cpp.i
.PHONY : src/chips/false.cpp.i

src/chips/false.s: src/chips/false.cpp.s
.PHONY : src/chips/false.s

# target to generate assembly for a file
src/chips/false.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/false.cpp.s
.PHONY : src/chips/false.cpp.s

src/chips/input.o: src/chips/input.cpp.o
.PHONY : src/chips/input.o

# target to build an object file
src/chips/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/input.cpp.o
.PHONY : src/chips/input.cpp.o

src/chips/input.i: src/chips/input.cpp.i
.PHONY : src/chips/input.i

# target to preprocess a source file
src/chips/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/input.cpp.i
.PHONY : src/chips/input.cpp.i

src/chips/input.s: src/chips/input.cpp.s
.PHONY : src/chips/input.s

# target to generate assembly for a file
src/chips/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/input.cpp.s
.PHONY : src/chips/input.cpp.s

src/chips/output.o: src/chips/output.cpp.o
.PHONY : src/chips/output.o

# target to build an object file
src/chips/output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/output.cpp.o
.PHONY : src/chips/output.cpp.o

src/chips/output.i: src/chips/output.cpp.i
.PHONY : src/chips/output.i

# target to preprocess a source file
src/chips/output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/output.cpp.i
.PHONY : src/chips/output.cpp.i

src/chips/output.s: src/chips/output.cpp.s
.PHONY : src/chips/output.s

# target to generate assembly for a file
src/chips/output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/output.cpp.s
.PHONY : src/chips/output.cpp.s

src/chips/true.o: src/chips/true.cpp.o
.PHONY : src/chips/true.o

# target to build an object file
src/chips/true.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/true.cpp.o
.PHONY : src/chips/true.cpp.o

src/chips/true.i: src/chips/true.cpp.i
.PHONY : src/chips/true.i

# target to preprocess a source file
src/chips/true.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/true.cpp.i
.PHONY : src/chips/true.cpp.i

src/chips/true.s: src/chips/true.cpp.s
.PHONY : src/chips/true.s

# target to generate assembly for a file
src/chips/true.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanotekspice.dir/build.make CMakeFiles/nanotekspice.dir/src/chips/true.cpp.s
.PHONY : src/chips/true.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nanotekspice"
	@echo "... src/chips/2716.o"
	@echo "... src/chips/2716.i"
	@echo "... src/chips/2716.s"
	@echo "... src/chips/4001.o"
	@echo "... src/chips/4001.i"
	@echo "... src/chips/4001.s"
	@echo "... src/chips/4008.o"
	@echo "... src/chips/4008.i"
	@echo "... src/chips/4008.s"
	@echo "... src/chips/4011.o"
	@echo "... src/chips/4011.i"
	@echo "... src/chips/4011.s"
	@echo "... src/chips/4013.o"
	@echo "... src/chips/4013.i"
	@echo "... src/chips/4013.s"
	@echo "... src/chips/4017.o"
	@echo "... src/chips/4017.i"
	@echo "... src/chips/4017.s"
	@echo "... src/chips/4030.o"
	@echo "... src/chips/4030.i"
	@echo "... src/chips/4030.s"
	@echo "... src/chips/4040.o"
	@echo "... src/chips/4040.i"
	@echo "... src/chips/4040.s"
	@echo "... src/chips/4069.o"
	@echo "... src/chips/4069.i"
	@echo "... src/chips/4069.s"
	@echo "... src/chips/4071.o"
	@echo "... src/chips/4071.i"
	@echo "... src/chips/4071.s"
	@echo "... src/chips/4081.o"
	@echo "... src/chips/4081.i"
	@echo "... src/chips/4081.s"
	@echo "... src/chips/4094.o"
	@echo "... src/chips/4094.i"
	@echo "... src/chips/4094.s"
	@echo "... src/chips/4512.o"
	@echo "... src/chips/4512.i"
	@echo "... src/chips/4512.s"
	@echo "... src/chips/4514.o"
	@echo "... src/chips/4514.i"
	@echo "... src/chips/4514.s"
	@echo "... src/chips/4801.o"
	@echo "... src/chips/4801.i"
	@echo "... src/chips/4801.s"
	@echo "... src/chips/clock.o"
	@echo "... src/chips/clock.i"
	@echo "... src/chips/clock.s"
	@echo "... src/chips/false.o"
	@echo "... src/chips/false.i"
	@echo "... src/chips/false.s"
	@echo "... src/chips/input.o"
	@echo "... src/chips/input.i"
	@echo "... src/chips/input.s"
	@echo "... src/chips/output.o"
	@echo "... src/chips/output.i"
	@echo "... src/chips/output.s"
	@echo "... src/chips/true.o"
	@echo "... src/chips/true.i"
	@echo "... src/chips/true.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

